repos:
-   hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
-   hooks:
    -   id: black
    repo: https://github.com/psf/black
    rev: 24.4.2
-   hooks:
    -   args:
        -   --fix
        -   --exit-non-zero-on-fix
        id: ruff
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.2
-   hooks:
    -   additional_dependencies:
        -   types-setuptools
        id: mypy
    repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
-   hooks:
    -   id: pre-commit-update
    repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.3.3post1
